modLoader = "javafml"
loaderVersion = "[2, )"
license = "MIT"

[[mods]]
modId = "forcepatch"
version = "1.0.3"
displayName = "ForcePatch"
updateJSONURL = ""
displayURL = ""
logoFile = ""
authorList = ["Tabitha"]
description = '''
A Minecraft mod that adds ForceCraft integration to various farming and automation mods.
'''
side = "CLIENT"

[[dependencies.forcepatch]]
modId = "neoforge"
mandatory = true
versionRange = "[21, )"
ordering = "NONE"
side = "CLIENT" 

[[dependencies.forcepatch]]
modId = "forcecraft"
mandatory = true
versionRange = "[0, )"
ordering = "NONE"
side = "CLIENT" 